[[configs]]
name = "UserLogin"
type = "Component"

[configs.component]
flagged = false
type = "Vec"
mask = false

[configs.fields.user_name]
type = "String"
field = 1

[configs.fields.passworld]
type = "String"
field = 2